# SignalPilot Jupyter Server Configuration (Defaults)
# This file is loaded by Jupyter Lab when running 'sp lab'
# DO NOT EDIT THIS FILE - it will be overwritten on upgrades.
# To customize settings, edit user-jupyter_server_config.py in the parent directory.

import os
from pathlib import Path

# Server settings
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.port = 8888
c.ServerApp.open_browser = True
c.ServerApp.token = ''  # Use token authentication by default
c.ServerApp.password = ''

# Root directory - set to user-workspace or team-workspace
# This is configured by the CLI when launching
# c.ServerApp.root_dir = str(Path.home() / 'SignalPilotHome' / 'user-workspace')

# Enable extensions
c.ServerApp.jpserver_extensions = {
    'jupyterlab': True
}

# Kernel settings
c.MultiKernelManager.default_kernel_name = 'python3'

# Security settings
c.ServerApp.disable_check_xsrf = False
c.ServerApp.allow_origin = '*'
c.ServerApp.allow_credentials = True

# Content management
c.ContentsManager.hide_globs = ['__pycache__', '*.pyc', '*.pyo', '.git', '.DS_Store']

# File save hooks (can be customized)
# c.FileContentsManager.post_save_hook = None
